process_output_fn:
  path: instruct/output_processing_scripts/gsm8k.py
  fn_name: process_output_cot_gsm8k
process_target_fn:
  path: instruct/output_processing_scripts/gsm8k.py
  fn_name: process_target_cot_gsm8k