hydra:
  run:
    dir: ${cache_path}/${task}/${model}/${dataset}/${now:%Y-%m-%d}/${now:%H-%M-%S}

defaults:
  - model: bloomz-560m
  - estimators: cot_estimators
  - stat_calculators: default_calculators
  - _self_

cache_path: ./workdir/output
save_path: '${hydra:run.dir}'
instruct: true
task: qa

dataset: ['denis1699/hotpot_cot']
text_column: question
label_column: answer
train_split: train
eval_split: validation
few_shot_prompt: null
max_new_tokens: 256
load_from_disk: false
normalize: true
trust_remote_code: false
size: 100


output_ignore_regex: "(?s).*Final Answer:"

subsample_eval_dataset: 10

generation_metrics: null

ignore_exceptions: false

batch_size: 1

seed:
    - 1
