_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.11.11
        t:
            "1":
                - 1
                - 5
                - 11
                - 33
                - 41
                - 49
                - 50
                - 51
                - 53
                - 55
                - 71
                - 75
                - 95
                - 100
            "2":
                - 1
                - 5
                - 11
                - 33
                - 41
                - 49
                - 50
                - 51
                - 53
                - 55
                - 71
                - 75
                - 95
                - 100
            "3":
                - 2
                - 15
                - 23
                - 55
            "4": 3.11.11
            "5": 0.19.11
            "6": 4.51.1
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
